name: Build SAF-CLI Windows/Linux Installers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: saf

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.18.0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: ./saf/pnpm-lock.yaml

      - name: Install Nullsoft Scriptable Install System and p7zip
        run: sudo apt install nsis p7zip-full

      - name: setup saf cli
        working-directory: ./saf
        run: |
          rm -rf test
          pnpm install --frozen-lockfile --prod

      - name: Pack Windows Installer
        working-directory: ./saf
        run: npx oclif pack win

      - name: Pack Debian Package
        working-directory: ./saf
        run: sudo npx oclif pack deb

      - name: Rename Windows Installers
        run: |
          cd saf/dist/win32
          for file in saf-*.exe; do
            prefix=${file%-*-*}     # get prefix by removing from end
            suffix=${file#saf-*-*-} # get suffix by removing from start
            mv "$file" "$prefix-$suffix"
          done

      - name: Rename Debian Installers
        run: |
          cd saf/dist/deb
          for file in saf_*.deb; do
            prefix=${file%.*-*.deb}
            prefix_ver=${prefix#saf_}
            suffix=${file#*_*_}
            sudo mv "$file" "saf-$prefix_ver-$suffix"
          done

      - name: Upload SAF-CLI Windows Build x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAF-CLI Windows Build x64
          path: saf/dist/win32/saf-*-x64.exe

      - name: Upload SAF-CLI Windows Build x86 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAF-CLI Windows Build x86
          path: saf/dist/win32/saf-*-x86.exe

      # underscore here since that's how the file is named
      - name: Upload SAF-CLI Debian x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAF-CLI Debian Build x64
          path: saf/dist/deb/saf-*.deb
